# -*- coding: utf-8 -*-
"""Machine Learning model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBKMwxZ8LfeW9yqVIsNnQJTsR3RkIBss
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score, recall_score, f1_score
import xgboost as xgb

# If you just ran Week 2 and features_df is still available, skip this.
# Otherwise, upload the CSV you downloaded earlier.
from google.colab import files
uploaded = files.upload()   # select 'pre_tournament_features_1998_2022.csv'

features_df = pd.read_csv('pre_tournament_features_1998_2022.csv')
features_df.head()

# List of numeric columns we want to keep
numeric_features = ['win_rate', 'goals_per_game', 'goals_conceded_per_game', 'fifa_rank', 'is_host']

# Create dummy variables for confederation (drop_first=True to avoid multicollinearity)
conf_dummies = pd.get_dummies(features_df['confederation'], prefix='conf', drop_first=True)

# Build the full feature matrix X
X = pd.concat([features_df[numeric_features], conf_dummies], axis=1)

# Target vector y
y = features_df['is_winner']

print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)
X.head()

# Split based on the 'year' column from the original features_df
train_mask = features_df['year'] < 2022
test_mask = features_df['year'] == 2022

X_train, X_test = X[train_mask], X[test_mask]
y_train, y_test = y[train_mask], y[test_mask]

print("Training samples:", X_train.shape[0])
print("Test samples:    ", X_test.shape[0])
print("Winners in train:", y_train.sum())
print("Winners in test: ", y_test.sum())

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train
logreg = LogisticRegression(max_iter=1000, class_weight='balanced')  # balanced to handle class imbalance
logreg.fit(X_train_scaled, y_train)

# Predict on test set (2022)
y_pred_log = logreg.predict(X_test_scaled)
y_prob_log = logreg.predict_proba(X_test_scaled)[:, 1]  # probability of being winner (class 1)

# Evaluation
print("========== Logistic Regression ==========")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log, target_names=['Non-winner', 'Winner']))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_log))

from sklearn.tree import DecisionTreeClassifier

# Train
dt = DecisionTreeClassifier(class_weight='balanced', random_state=42)
dt.fit(X_train_scaled, y_train)

# Predict
y_pred_dt = dt.predict(X_test_scaled)
y_prob_dt = dt.predict_proba(X_test_scaled)[:, 1]

# Evaluation
print("========== Decision Tree ==========")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt, target_names=['Non-winner', 'Winner']))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))

# Top 5 predicted winners (2022)
test_teams['win_probability_dt'] = y_prob_dt
top5_dt = test_teams.sort_values('win_probability_dt', ascending=False).head(5)
print("\nTop 5 predicted by Decision Tree:")
print(top5_dt[['team', 'win_probability_dt']])

from sklearn.naive_bayes import GaussianNB

# Train
nb = GaussianNB()
nb.fit(X_train_scaled, y_train)

# Predict
y_pred_nb = nb.predict(X_test_scaled)
y_prob_nb = nb.predict_proba(X_test_scaled)[:, 1]

# Evaluation
print("========== Gaussian Naive Bayes ==========")
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print("\nClassification Report:\n", classification_report(y_test, y_pred_nb, target_names=['Non-winner', 'Winner']))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))

# Top 5
test_teams['win_probability_nb'] = y_prob_nb
top5_nb = test_teams.sort_values('win_probability_nb', ascending=False).head(5)
print("\nTop 5 predicted by Naive Bayes:")
print(top5_nb[['team', 'win_probability_nb']])

# Add predictions to the 2022 subset for inspection
test_teams = features_df[test_mask][['team', 'year']].copy()
test_teams['win_probability'] = y_prob_log
test_teams['predicted_winner'] = y_pred_log

# Show the top 5 teams by predicted probability
test_teams.sort_values('win_probability', ascending=False).head(5)

#Random Forest
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf.fit(X_train_scaled, y_train)

y_pred_rf = rf.predict(X_test_scaled)
y_prob_rf = rf.predict_proba(X_test_scaled)[:, 1]

print("========== Random Forest ==========")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf, target_names=['Non-winner', 'Winner']))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

test_teams['win_probability_rf'] = y_prob_rf
test_teams['predicted_winner_rf'] = y_pred_rf
test_teams.sort_values('win_probability_rf', ascending=False).head(5)

#XGBoost
xgb_model = xgb.XGBClassifier(scale_pos_weight=(y_train==0).sum() / y_train.sum(),  # handles imbalance
                              use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_model.fit(X_train_scaled, y_train)

y_pred_xgb = xgb_model.predict(X_test_scaled)
y_prob_xgb = xgb_model.predict_proba(X_test_scaled)[:, 1]

print("========== XGBoost ==========")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb, target_names=['Non-winner', 'Winner']))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))

test_teams['win_probability_xgb'] = y_prob_xgb
test_teams['predicted_winner_xgb'] = y_pred_xgb
test_teams.sort_values('win_probability_xgb', ascending=False).head(5)

results = {
    'Model': ['Logistic Regression', 'Random Forest', 'XGBoost', 'Decision Tree', 'Naive Bayes'],
    'Accuracy': [
        accuracy_score(y_test, y_pred_log),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_xgb),
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_nb)
    ],
    'Precision (Winner)': [
        precision_score(y_test, y_pred_log, zero_division=0),
        precision_score(y_test, y_pred_rf, zero_division=0),
        precision_score(y_test, y_pred_xgb, zero_division=0),
        precision_score(y_test, y_pred_dt, zero_division=0),
        precision_score(y_test, y_pred_nb, zero_division=0)
    ],
    'Recall (Winner)': [
        recall_score(y_test, y_pred_log),
        recall_score(y_test, y_pred_rf),
        recall_score(y_test, y_pred_xgb),
        recall_score(y_test, y_pred_dt),
        recall_score(y_test, y_pred_nb)
    ],
    'F1 (Winner)': [
        f1_score(y_test, y_pred_log),
        f1_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_xgb),
        f1_score(y_test, y_pred_dt),
        f1_score(y_test, y_pred_nb)
    ]
}

comparison_df = pd.DataFrame(results).set_index('Model')
comparison_df.sort_values('F1 (Winner)', ascending=False)

# Find the index of Argentina in the 2022 test set
test_indices = features_df[test_mask].index
argentina_idx = features_df[test_mask]['team'].values == 'Argentina'
if argentina_idx.sum() == 0:
    print("Argentina not found in test set – check team name!")
else:
    arg_position = np.where(argentina_idx)[0][0]
    print(f"Argentina is at test array position {arg_position}\n")

    # Dictionary of model name → probability array
    probs = {
        'Logistic Regression': y_prob_log,
        'Naive Bayes': y_prob_nb,
        'Random Forest': y_prob_rf,
        'XGBoost': y_prob_xgb,
        'Decision Tree': y_prob_dt
    }

    print("Rank of Argentina (1 = highest probability, 32 = lowest):")
    for name, prob_array in probs.items():
        # Rank Argentina among all 32 teams (higher prob = better)
        sorted_indices = np.argsort(prob_array)[::-1]  # descending
        rank = np.where(sorted_indices == arg_position)[0][0] + 1
        print(f"{name:25s} → Rank {rank}/32")

#2026 world-cup winner through logistic Regression

#Import libraries and load the match data
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Load match results
url_matches = "https://raw.githubusercontent.com/martj42/international_results/master/results.csv"
all_matches = pd.read_csv(url_matches)
all_matches['date'] = pd.to_datetime(all_matches['date'])

# Load FIFA rankings (use the file you uploaded earlier)
from google.colab import files
uploaded = files.upload()   # select your fifa_ranking CSV (e.g., 'fifa_ranking-2024-04-04 (1).csv')
rankings = pd.read_csv('fifa_ranking-2024-04-04.csv')  # adjust filename
rankings['rank_date'] = pd.to_datetime(rankings['rank_date'])

print("Match data loaded:", all_matches.shape)
print("Rankings loaded:", rankings.shape)

# Upload the feature table CSV you downloaded at the end of Week 2
uploaded = files.upload()   # select 'pre_tournament_features_1998_2022.csv'
features_df = pd.read_csv('pre_tournament_features_1998_2022.csv')
features_df.head()

# Prepare features and target
numeric_features = ['win_rate', 'goals_per_game', 'goals_conceded_per_game', 'fifa_rank', 'is_host']
conf_dummies = pd.get_dummies(features_df['confederation'], prefix='conf', drop_first=True)
X = pd.concat([features_df[numeric_features], conf_dummies], axis=1)
y = features_df['is_winner']

# Split train/test (train up to 2018, test 2022)
train_mask = features_df['year'] < 2022
test_mask = features_df['year'] == 2022
X_train, X_test = X[train_mask], X[test_mask]
y_train, y_test = y[train_mask], y[test_mask]

# Scale
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Logistic Regression
logreg = LogisticRegression(max_iter=1000, class_weight='balanced')
logreg.fit(X_train_scaled, y_train)

# Quick check on 2022 rank (so we know it works)
y_prob = logreg.predict_proba(X_test_scaled)[:, 1]
test_indices = features_df[test_mask].index
argentina_idx = features_df.loc[test_mask, 'team'].values == 'Argentina'
argentina_rank = np.where(np.argsort(y_prob)[::-1] == np.where(argentina_idx)[0][0])[0][0] + 1
print("Argentina 2022 rank (Logistic Regression):", argentina_rank)

print('all_matches' in dir())
print('rankings' in dir())
print('logreg' in dir())
print('scaler' in dir())
print('X' in dir())
print('name_corrections' in dir())

name_corrections = {
    'United States': 'USA',
    'Korea Republic': 'South Korea',
    'Korea DPR': 'North Korea',
    'IR Iran': 'Iran',
    'Côte d\'Ivoire': 'Ivory Coast',
    'Bosnia and Herzegovina': 'Bosnia-Herzegovina',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Serbia': 'Serbia',
    'Montenegro': 'Montenegro',
    'East Germany': 'German DR',
    'West Germany': 'Germany',
    'Soviet Union': 'USSR',
    'Czechoslovakia': 'Czechoslovakia',
    'Yugoslavia': 'Yugoslavia',
    'Zaire': 'DR Congo',
    'Dutch East Indies': 'Indonesia'
}

print('all_matches' in dir())
print('rankings' in dir())
print('logreg' in dir())
print('scaler' in dir())
print('X' in dir())
print('name_corrections' in dir())

# Your actual 48 teams from the official group stage draw
teams_2026 = [
    'Mexico', 'South Africa', 'South Korea', 'Czechia',
    'Canada', 'Bosnia and Herzegovina', 'Qatar', 'Switzerland',
    'Brazil', 'Morocco', 'Haiti', 'Scotland',
    'USA', 'Paraguay', 'Australia', 'Turkey',
    'Germany', 'Curacao', 'Ivory Coast', 'Ecuador',
    'Netherlands', 'Japan', 'Sweden', 'Tunisia',
    'Belgium', 'Egypt', 'Iran', 'New Zealand',
    'Spain', 'Cape Verde', 'Saudi Arabia', 'Uruguay',
    'France', 'Senegal', 'Iraq', 'Norway',
    'Argentina', 'Algeria', 'Austria', 'Jordan',
    'Portugal', 'DR Congo', 'Uzbekistan', 'Colombia',
    'England', 'Croatia', 'Ghana', 'Panama'
]

# Corrected mapping – only the names that REALLY differ in the match dataset
name_map_to_match = {
    'USA': 'United States',       # matches use 'United States'
    'Czechia': 'Czech Republic',  # matches use 'Czech Republic'
    'Turkey': 'Turkey',           # fine (both the same)
    'Curacao': 'Curaçao',         # matches use 'Curaçao'
    'DR Congo': 'DR Congo',       # already correct
    'Cape Verde': 'Cape Verde',   # fine
    # All others (South Korea, Iran, Ivory Coast, etc.) are exactly the same in the match data
}

# Convert team names
teams_2026_match = [name_map_to_match.get(t, t) for t in teams_2026]

# Verify: no name should be missing now
match_teams = pd.concat([all_matches['home_team'], all_matches['away_team']]).unique()
missing = [t for t in teams_2026_match if t not in match_teams]
print("Still missing:", missing)

# Check what names exist in the match data that contain these substrings
search_terms = ['Korea', 'Ivoire', 'Iran', 'Congo', 'Cura']
for term in search_terms:
    matches = [name for name in match_teams if term.lower() in name.lower()]
    print(f"'{term}' → {matches}")

##Compute the 2026 features
# Time window: 2 years before the 2026 tournament starts (11 June 2026)
start_2026 = pd.to_datetime('2026-06-11')
window_start = start_2026 - timedelta(days=730)
window_end   = start_2026

# All matches inside that window (up to the day before the tournament)
recent_2026 = all_matches[(all_matches['date'] >= window_start) &
                          (all_matches['date'] < window_end)]

# Host nations (as they appear in the match dataset)
hosts_2026 = ['United States', 'Canada', 'Mexico']

rows_2026 = []

for team in teams_2026_match:
    # Matches involving this team (home or away)
    team_matches = recent_2026[(recent_2026['home_team'] == team) |
                               (recent_2026['away_team'] == team)]
    if len(team_matches) == 0:
        continue   # skip if no recent matches (very unlikely for a qualified team)

    goals_scored = 0
    goals_conceded = 0
    wins = 0
    draws = 0
    losses = 0

    for _, m in team_matches.iterrows():
        if m['home_team'] == team:
            goals_scored += m['home_score']
            goals_conceded += m['away_score']
            if m['home_score'] > m['away_score']:
                wins += 1
            elif m['home_score'] == m['away_score']:
                draws += 1
            else:
                losses += 1
        else:   # team played away
            goals_scored += m['away_score']
            goals_conceded += m['home_score']
            if m['away_score'] > m['home_score']:
                wins += 1
            elif m['away_score'] == m['home_score']:
                draws += 1
            else:
                losses += 1

    total_matches = wins + draws + losses
    win_rate = wins / total_matches
    goals_pg = goals_scored / total_matches
    goals_conceded_pg = goals_conceded / total_matches

    # FIFA rank: look up using the original name_corrections (to convert match‑name → ranking‑name)
    ranking_name = name_corrections.get(team, team)   # e.g., 'United States' → 'USA'
    team_ranks = rankings[(rankings['country_full'] == ranking_name) &
                          (rankings['rank_date'] < window_end)]
    if len(team_ranks) > 0:
        latest_rank = team_ranks.iloc[-1]['rank']
        conf = team_ranks.iloc[-1]['confederation']
    else:
        latest_rank = 200   # fallback
        conf = 'Unknown'

    is_host = 1 if team in hosts_2026 else 0

    rows_2026.append({
        'team': team,
        'win_rate': win_rate,
        'goals_per_game': goals_pg,
        'goals_conceded_per_game': goals_conceded_pg,
        'fifa_rank': latest_rank,
        'is_host': is_host,
        'confederation': conf
    })

features_2026 = pd.DataFrame(rows_2026)
print("Teams with recent matches:", len(features_2026))
features_2026.head()

# Add missing mappings (these are needed for FIFA rank lookup)
name_corrections['South Korea'] = 'Korea Republic'     # match data uses 'South Korea', ranking uses 'Korea Republic'
name_corrections['Czech Republic'] = 'Czech Republic'   # maybe ranking uses 'Czech Republic'? We'll try; if not, we'll search

features_2026[features_2026['team'].isin(['South Korea', 'Czech Republic'])][['team', 'fifa_rank', 'confederation']]

# Find all unique country names in the ranking file that contain these substrings
search_for = ['Korea', 'Czech']
for term in search_for:
    matches = rankings['country_full'].unique()
    matches = [m for m in matches if term.lower() in m.lower()]
    print(f"'{term}' in ranking file → {matches}")

# Add missing match‑name → ranking‑name mappings
name_corrections['South Korea'] = 'Korea Republic'   # match → ranking
name_corrections['Czech Republic'] = 'Czechia'       # match → ranking

#Predict 2026 Fifa world cup winner
# 1. Prepare the feature matrix X_2026 (same columns as training X)
numeric_features = ['win_rate', 'goals_per_game', 'goals_conceded_per_game', 'fifa_rank', 'is_host']
conf_dummies_2026 = pd.get_dummies(features_2026['confederation'], prefix='conf', drop_first=True)
X_2026 = pd.concat([features_2026[numeric_features], conf_dummies_2026], axis=1)

# 2. Align with training columns (any missing confederation dummies become 0)
X_2026 = X_2026.reindex(columns=X.columns, fill_value=0)

# 3. Scale using the SAME scaler fitted on the historical training data
X_2026_scaled = scaler.transform(X_2026)

# 4. Predict win probabilities using our BEST model – Logistic Regression
proba_2026 = logreg.predict_proba(X_2026_scaled)[:, 1]
features_2026['win_probability'] = proba_2026

# 5. Show the TOP 10 most likely winners
top10 = features_2026.sort_values('win_probability', ascending=False).head(10)
print("🏆 Top 10 predicted teams for the 2026 FIFA World Cup:")
print(top10[['team', 'win_probability', 'fifa_rank', 'is_host']].to_string(index=False))

# 6. (Optional) Show the full 48-team list sorted
# features_2026_sorted = features_2026.sort_values('win_probability', ascending=False)
# features_2026_sorted[['team', 'win_probability']].head(20)

