# -*- coding: utf-8 -*-
"""WorldCup_FeatureEngineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-tlFkTZ3YPrrd0EpgL7CPXuAHMhvmZ90
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Load the complete results (1872 to 2024)
url_matches = "https://raw.githubusercontent.com/martj42/international_results/master/results.csv"
all_matches = pd.read_csv(url_matches)

# Convert date to datetime
all_matches['date'] = pd.to_datetime(all_matches['date'])

# Check the range
print("Earliest match:", all_matches['date'].min())
print("Latest match:", all_matches['date'].max())

wc_finals = all_matches[all_matches['tournament'].str.contains('FIFA World Cup', na=False) &
                        ~all_matches['tournament'].str.contains('qualification', na=False)].copy()
wc_finals[['date', 'home_team', 'away_team', 'tournament']].head()

# Keep only World Cups from 1998 to 2022 (no future ones)
tournaments = tournaments[(tournaments['tournament_year'] >= 1998) &
                          (tournaments['tournament_year'] <= 2022)]

host_dict = {
    'FIFA World Cup 1998': 'France',
    'FIFA World Cup 2002': 'South Korea',
    'FIFA World Cup 2006': 'Germany',
    'FIFA World Cup 2010': 'South Africa',
    'FIFA World Cup 2014': 'Brazil',
    'FIFA World Cup 2018': 'Russia',
    'FIFA World Cup 2022': 'Qatar'
}

winners = {
    'FIFA World Cup 1998': 'France',
    'FIFA World Cup 2002': 'Brazil',
    'FIFA World Cup 2006': 'Italy',
    'FIFA World Cup 2010': 'Spain',
    'FIFA World Cup 2014': 'Germany',
    'FIFA World Cup 2018': 'France',
    'FIFA World Cup 2022': 'Argentina'
}

from google.colab import files
upload = files.upload()

# Replace the filename with the exact name of the CSV you uploaded
rankings = pd.read_csv('fifa_ranking-2024-04-04 (1).csv')   # <-- adjust if needed
rankings['rank_date'] = pd.to_datetime(rankings['rank_date'])

rankings.head()

print("Earliest rank date:", rankings['rank_date'].min())
print("Latest rank date:  ", rankings['rank_date'].max())

# Name‑correction dictionary & window size
# Map team names from the match dataset to the ranking dataset
name_corrections = {
    'United States': 'USA',
    'Korea Republic': 'South Korea',
    'Korea DPR': 'North Korea',
    'IR Iran': 'Iran',
    'Côte d\'Ivoire': 'Ivory Coast',
    'Bosnia and Herzegovina': 'Bosnia-Herzegovina',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Serbia': 'Serbia',
    'Montenegro': 'Montenegro',
    'East Germany': 'German DR',
    'West Germany': 'Germany',
    'Soviet Union': 'USSR',
    'Czechoslovakia': 'Czechoslovakia',
    'Yugoslavia': 'Yugoslavia',
    'Zaire': 'DR Congo',
    'Dutch East Indies': 'Indonesia'
}

WINDOW_DAYS = 730   # 2 years before the tournament starts

# Only FIFA World Cup finals matches (exact match is safer)
wc_finals = all_matches[all_matches['tournament'] == 'FIFA World Cup'].copy()

# Add a year column for grouping
wc_finals['wc_year'] = wc_finals['date'].dt.year

# For each edition, get the start date
tournaments = wc_finals.groupby('wc_year').agg(
    start_date=('date', 'min')
).reset_index()

# Rename column for clarity
tournaments.rename(columns={'wc_year': 'tournament_year'}, inplace=True)

# Keep only modern editions (1998+)
tournaments = tournaments[tournaments['tournament_year'] >= 1998]

tournaments

host_dict = {
    1998: 'France',
    2002: 'South Korea',
    2006: 'Germany',
    2010: 'South Africa',
    2014: 'Brazil',
    2018: 'Russia',
    2022: 'Qatar'
}

winners = {
    1998: 'France',
    2002: 'Brazil',
    2006: 'Italy',
    2010: 'Spain',
    2014: 'Germany',
    2018: 'France',
    2022: 'Argentina'
}

feature_rows = []

for _, tourn in tournaments.iterrows():
    year = tourn['tournament_year']
    start_date = tourn['start_date']

    host = host_dict[year]
    winner = winners[year]

    # Matches from this specific World Cup (same year, same tournament)
    tourn_matches = wc_finals[wc_finals['wc_year'] == year]
    teams = pd.concat([tourn_matches['home_team'], tourn_matches['away_team']]).unique()

    window_end = start_date
    window_start = window_end - timedelta(days=WINDOW_DAYS)

    # Recent matches (excluding this tournament's year to avoid leakage)
    recent_matches = all_matches[(all_matches['date'] >= window_start) &
                                 (all_matches['date'] < window_end) &
                                 ~((all_matches['tournament'] == 'FIFA World Cup') &
                                   (all_matches['date'].dt.year == year))]  # exclude finals from this year

    print(f"Processing World Cup {year}: {len(teams)} teams, {len(recent_matches)} recent matches")

    for team in teams:
        team_matches = recent_matches[(recent_matches['home_team'] == team) |
                                      (recent_matches['away_team'] == team)]
        if len(team_matches) == 0:
            continue

        goals_scored = 0
        goals_conceded = 0
        wins = 0
        draws = 0
        losses = 0

        for _, m in team_matches.iterrows():
            if m['home_team'] == team:
                goals_scored += m['home_score']
                goals_conceded += m['away_score']
                if m['home_score'] > m['away_score']:
                    wins += 1
                elif m['home_score'] == m['away_score']:
                    draws += 1
                else:
                    losses += 1
            else:
                goals_scored += m['away_score']
                goals_conceded += m['home_score']
                if m['away_score'] > m['home_score']:
                    wins += 1
                elif m['away_score'] == m['home_score']:
                    draws += 1
                else:
                    losses += 1

        total_matches = wins + draws + losses
        win_rate = wins / total_matches
        goals_pg = goals_scored / total_matches
        goals_conceded_pg = goals_conceded / total_matches

        corrected_name = name_corrections.get(team, team)
        team_rankings = rankings[(rankings['country_full'] == corrected_name) &
                                 (rankings['rank_date'] < window_end)]
        if len(team_rankings) > 0:
            latest_rank = team_rankings.iloc[-1]['rank']
            conf = team_rankings.iloc[-1]['confederation']
        else:
            latest_rank = 200
            conf = 'Unknown'

        is_host = 1 if team == host else 0
        is_winner = 1 if team == winner else 0

        feature_rows.append({
            'tournament': f"World Cup {year}",
            'year': year,
            'start_date': start_date,
            'team': team,
            'win_rate': win_rate,
            'goals_per_game': goals_pg,
            'goals_conceded_per_game': goals_conceded_pg,
            'fifa_rank': latest_rank,
            'is_host': is_host,
            'confederation': conf,
            'is_winner': is_winner
        })

# Create DataFrame
features_df = pd.DataFrame(feature_rows)
features_df.head()

print("Winners per tournament:")
print(features_df['is_winner'].groupby(features_df['tournament']).sum())

features_df.to_csv('pre_tournament_features_1998_2022.csv', index=False)
from google.colab import files
files.download('pre_tournament_features_1998_2022.csv')

